import math

print(math.pi)
print(math.inf)
print("==============ceil anf floor===============")
print(math.ceil(1.4))
print(math.floor(1.4))
print(math.ceil(-5.3))
print(math.floor(-5.3))
print(math.ceil(10.0))
print(math.floor(10.0))
print(math.ceil(0.1))
print(math.floor(0.1))
print("=============cos================")
print(math.cos(0.00))
print(math.cos(1.0))
print(math.cos(10.0))
print("==============sin===============")
print(math.sin(1.0))
print(math.sin(0.00))
print("===============tan==============")
print(math.tan(0))
print(math.tan(1))
print("==============degrees===============")
print(math.degrees(8.90))
print(math.degrees(-20))
print(math.degrees(1))
print(math.degrees(90))
print("==============absolute==============")
print(math.fabs(-66.43))
print(math.fabs(-7))
print("=============factorial===============")
print(math.factorial(5))
print("==============mod==============")
print(math.fmod(20,4))
print(math.fmod(20,6))
print("==============sum==============")
print(math.fsum([1,2,3,4,5,6,7]))
print("==============product================")
print(math.gcd(5,10,15,20))
print("==============finite=================")
print(math.isfinite(5))
print("==============infinite===============")
print(math.isinf(math.inf))
print(math.isinf(10))
print("==============not a number===============")
print(math.isnan(1000))
print(math.isnan(float("nan")))
print(math.isnan(math.nan))
print("=============power of====================")
print(math.pow(3,9))
print("==============sqrt=====================")
print(math.sqrt(25))